#!/bin/bash
if [[ ! -e sseutils64.o ]]; then nasm -f elf64 sseutils64.nasm; fi;
nasm -f elf64 cfs64.nasm
gcc -m64 -msse -mavx -O0 -no-pie sseutils64.o cfs64.o cfs64c.c -o cfs64c -lm
pars="";
for arg; do pars=$pars" "$arg; done;
./cfs64c $pars
